### PR TITLE
Cython support.

### PR DESCRIPTION
**Pull request by anntzer**
Just making indents after cdef and cpdef similar to def.  The variable
must be made buffer-local in case one is editing both Python and Cython
sources at the same time.

### CODE REVIEW

**Comment by blueyed** [comment]
:+1: 

Although I would not add the .gitignore - but it's OK.

@hynek 
Any objections?

**Comment by hynek** [comment]
added functionality without modifications to tests are highly suspicious :)

**Comment by anntzer** [comment]
Here we go.

**Comment by hynek** [comment]
Cool, Leaving it up to @blueyed :)

**Comment by blueyed** [comment]
Awesome, thank you very much!

**Pull request merged**
