### PR TITLE
Fix indenting of strings after opening paren

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/hynek/vim-python-pep8-indent/issues/36

First attempt: c462de6

### CODE REVIEW

**Comment by blueyed** [comment]
@hynek 
Any feedback on this? :)

**Comment by hynek** [comment]
Is “it’s a lot of code and I have a bad conscious for not having reviewed it yet” a valid answer? :)

In all seriousness: for me to understand and review these changes would take hours of re-reading VimL docs.  I think I’ll just give you commit rights and you promise to wield them responsibly? :)

**Comment by blueyed** [comment]
> I think I’ll just give you commit rights and you promise to wield them responsibly? :)

Ok, thanks!

But feedback on the spec would be helpful of course, i.e. does it behave like you'd like it to do?

**Comment by hynek** [comment]
You should have merge rights now.  Which indentation scheme did you choose in the end?  Although I hate the dedent-approach it seems to be the more common one.  So I guess I could live with it.

**Comment by blueyed** [comment]
It falls back to 0.

I won't change it for now, but we could change this later.

**Pull request closed without merging**
